<?php
      echo '<p>' .__('Thank you for using Artistography.  It was conceptualized in mid-2010, and came to be manifested as a wordpress Plugin beginning around January 6th, 2011.  Developed by Chad Harrington (also known as Mistah Write from <a href="http://www.SpruceGooseRecords.com" target="_blank">www.SpruceGooseRecords.com</a>).  It was developed with PHP 5, MySQL 5, and Wordpress v3.0.4', $i18n_domain). '</p>';
      echo '<p>' .sprintf(__('Version: %s', $i18n_domain), ARTISTOGRAPHY_VERSION). '</p>';
?>